/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author ninte
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jm_login = new javax.swing.JMenu();
        jmi_inicio = new javax.swing.JMenuItem();
        jm_menu = new javax.swing.JMenu();
        jmi_clientes = new javax.swing.JMenuItem();
        jmi_con_compra = new javax.swing.JMenuItem();
        jmi_compra = new javax.swing.JMenuItem();
        jmi_detalleCompras = new javax.swing.JMenuItem();
        jmi_detalleCompra = new javax.swing.JMenuItem();
        jmi_detalleVentas = new javax.swing.JMenuItem();
        jmi_empleados = new javax.swing.JMenuItem();
        jmi_productos = new javax.swing.JMenuItem();
        jmi_proveedores = new javax.swing.JMenuItem();
        jmi_ventas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jm_login.setText("Login");

        jmi_inicio.setText("Inicio de sesion");
        jm_login.add(jmi_inicio);

        jMenuBar1.add(jm_login);

        jm_menu.setText("Menu");
        jm_menu.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N

        jmi_clientes.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_clientes.setText("Clientes");
        jm_menu.add(jmi_clientes);

        jmi_con_compra.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_con_compra.setText("Consulta Compras");
        jmi_con_compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_con_compraActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_con_compra);

        jmi_compra.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_compra.setText("Compra");
        jm_menu.add(jmi_compra);

        jmi_detalleCompras.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_detalleCompras.setText("Consulta Detalle de Compras");
        jmi_detalleCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_detalleComprasActionPerformed(evt);
            }
        });
        jm_menu.add(jmi_detalleCompras);

        jmi_detalleCompra.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_detalleCompra.setText("Detalle Compra");
        jm_menu.add(jmi_detalleCompra);

        jmi_detalleVentas.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_detalleVentas.setText("Detalle de Venta");
        jm_menu.add(jmi_detalleVentas);

        jmi_empleados.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_empleados.setText("Empleados");
        jm_menu.add(jmi_empleados);

        jmi_productos.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_productos.setText("Productos");
        jm_menu.add(jmi_productos);

        jmi_proveedores.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_proveedores.setText("Proveedores");
        jm_menu.add(jmi_proveedores);

        jmi_ventas.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 12)); // NOI18N
        jmi_ventas.setText("Ventas");
        jm_menu.add(jmi_ventas);

        jMenuBar1.add(jm_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 591, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_con_compraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_con_compraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_con_compraActionPerformed

    private void jmi_detalleComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_detalleComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_detalleComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jm_login;
    public javax.swing.JMenu jm_menu;
    public javax.swing.JMenuItem jmi_clientes;
    public javax.swing.JMenuItem jmi_compra;
    public javax.swing.JMenuItem jmi_con_compra;
    public javax.swing.JMenuItem jmi_detalleCompra;
    public javax.swing.JMenuItem jmi_detalleCompras;
    public javax.swing.JMenuItem jmi_detalleVentas;
    public javax.swing.JMenuItem jmi_empleados;
    public javax.swing.JMenuItem jmi_inicio;
    public javax.swing.JMenuItem jmi_productos;
    public javax.swing.JMenuItem jmi_proveedores;
    public javax.swing.JMenuItem jmi_ventas;
    // End of variables declaration//GEN-END:variables
}
